import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Box, Container, Typography, styled } from "@mui/material";
import Hero from "../components/organisms/Hero/Hero";
import { ColorResources } from "../models/colorResources";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Casa Emanuel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ backgroundColor: "#00000088", width: "100%" }}>
        <Hero
          post={{
            description: "",
            imageText: "",
            linkText: "",
            title: "",
            image:
              "https://scontent.fgye1-1.fna.fbcdn.net/v/t39.30808-6/327439760_908153513693288_36842327819730405_n.png?_nc_cat=109&cb=99be929b-3346023f&ccb=1-7&_nc_sid=e3f864&_nc_eui2=AeF5JaIUjPRBJCrmMZOBAlkIXi6TuYKrgpZeLpO5gquClqQttp2lGZmiWlwm8lCJY_Q&_nc_ohc=zxz2yG4bG3oAX9lIJvN&_nc_ht=scontent.fgye1-1.fna&oh=00_AfCXMOQhqnFGSM3g2cni_Ah8VYLOagA2h_rs9lidZtPErg&oe=64B8E465",
          }}
        />
        <Box sx={{ pt: 6, pb: 6, backgroundColor: ColorResources.PRIMARY_TINT1}}>
          <Typography typography={"h2"} align="center" color={ColorResources.WHITE} fontWeight={400}>
          Bienvenido a la Iglesia<br/> para las familias
          </Typography>
        </Box>
      </Box>
    </>
  );
}
